package features;

public enum SharedDataName {
    CREATE_DASHCAM_RESPONSE,
    LEASE_DASHCAM_RESPONSE,
    INSTALL_DASHCAM_RESPONSE,
    ASSIGN_DASHCAM_RESPONSE,
    UNASSIGN_DASHCAM_RESPONSE,
    UNINSTALL_DASHCAM_RESPONSE,
    CREATE_DASHCAM_RESPONSE_PARAMETERIZED
}
